export default {
  backgroundImage: require("../../assets/image/background5.jpg"),
  myntraLogo: require("../../assets/image/myntra.png"),
  facebook: require("../../assets/image/facebook.png"),
  google: require("../../assets/image/google.png"),
  menu: require("../../assets/image/menu.png"),
  search: require("../../assets/image/search.png"),
  notification: require("../../assets/image/notification.png"),
  wishlist: require("../../assets/image/wishlist.png"),
  cart: require("../../assets/image/cart.png"),
  scrollSale: require("../../assets/image/sale.jpg"),
  scrollMen: require("../../assets/image/men.jpg"),
  scrollWomen: require("../../assets/image/women.jpg"),
  scrollkid: require("../../assets/image/kid.jpg"),
  scrollBeauty: require("../../assets/image/beauty.jpg"),
  scrollHome: require("../../assets/image/home.jpg"),
  backButton: require("../../assets/image/back.png"),
  emailButton: require("../../assets/image/email.png"),
  phoneButton: require("../../assets/image/phone.png"),
  shareButton: require("../../assets/image/share.png"),
  trackButton: require("../../assets/image/track.png"),
  boxButton: require("../../assets/image/box.png"),
  rightButton: require("../../assets/image/rightArrow.png"),
  helpButton: require("../../assets/image/help.png"),
  kingButton: require("../../assets/image/king.png"),
  legButton: require("../../assets/image/leg.png"),
};
